### ISSUE TITLE
Bring to front

### ISSUE THREAD

**Issue by dirtslayer** [JCAguilera/better-drag-and-drop-sprite#3]
I wanted the selected sprite to come to the front. If you would like to see how I did this, I wouldnt mind some comments

The general method was after a card was selected, set its z-order to the top and any cards that where previously above it move down by 1 

i tried to use another method which used set_input_as_handled() , but failed,

https://www.reddit.com/r/godot/comments/7xwr22/guide_how_to_click_a_sprite/

check out this repo for my variation

https://github.com/dirtslayer/gdcards

**Comment by JCAguilera** [comment]
Sorry for the late response, I think the z-order method works fine, although it may affect performance with many sprites.
